name: NuGet Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # permission for the github token
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x' # No change it
          source-url: https://nuget.pkg.github.com/NNT-ADevStudio/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build project
        run: dotnet build --configuration Release
      - name: Create the package
        run: dotnet pack --configuration Release --output bin/Release
      - name: Publish the package to GPR
        run: dotnet nuget push bin/Release/*.nupkg --skip-duplicate
        
